### ISSUE TITLE
Gérer la commande d'un nouveau projet

### ISSUE THREAD

**Issue by clairenollet** [dnum-mi/dso-console#20]
Gérer ce qu'il se passe au `orderProject()` dans `OrderProject.vue`

## TODO

- [x] envoyer toutes ces infos à une API (qu'il faut créer) 
- [x] pour ensuite les stocker dans une base de données (`postgresql` a priori) 
- [x] déclencher des scripts `ansible` (déclenchement de ces script par l'API) qui permettront de créer les espaces projet dans les différents services (gitlab, vault, nexus , etc...)
- [x] générer des variables (token, etc...) qu'il nous faudra afficher à l'utilisateur dans son espace projet de la console

_Originally posted by @this-is-tobi in https://github.com/dnum-mi/dso-console/issues/19#issuecomment-1264415334_

```JS
project: {
  email: string (regex `email`),
  orgName: string (`orgOptions`),
  projectName: string (`noSpace`),
  repo: [{
    gitName: string (`noSpace`),
    gitSourceName: string,
    managerName: string,
    isPrivate: boolean,
    gitToken: string
  },
  {
    gitName: string (`noSpace`),
    gitSourceName: string,
    managerName: string,
    isPrivate: boolean,
    gitToken: string
  },
  [etc.]],
}
```
